// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cafe.Data;

#nullable disable

namespace cafe.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    [Migration("20260628133954_AddNewProductsAndNullableAddress")]
    partial class AddNewProductsAndNullableAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cafe.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("cafe.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("cafe.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kahve",
                            Description = "Yoğun kıvamlı ve zengin aromalı klasik İtalyan espressosu.",
                            ImageUrl = "https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?q=80&w=300",
                            IsActive = true,
                            Name = "Espresso",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kahve",
                            Description = "Espresso, buharla ısıtılmış süt ve üzerinde hafif süt köpüğü.",
                            ImageUrl = "https://images.unsplash.com/photo-1570968915860-54d5c301fc9f?q=80&w=300",
                            IsActive = true,
                            Name = "Caffe Latte",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Kahve",
                            Description = "Sıcak su ile yumuşatılmış zengin Espresso lezzeti.",
                            ImageUrl = "https://images.unsplash.com/photo-1551046713-bc755f487116?q=80&w=300",
                            IsActive = true,
                            Name = "Americano",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kahve",
                            Description = "Geleneksel yöntemlerle cezvede pişirilmiş, bol köpüklü klasik Türk kahvesi.",
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=300",
                            IsActive = true,
                            Name = "Türk Kahvesi",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tatlı",
                            Description = "İçi yumuşacık ve akışkan, üzeri karamelize yanık İspanyol cheesecake'i.",
                            ImageUrl = "https://images.unsplash.com/photo-1524351199679-46cddf530c04?q=80&w=300",
                            IsActive = true,
                            Name = "San Sebastian Cheesecake",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tatlı",
                            Description = "Sıcak servis edilen, içi akışkan çikolatalı nefis sufle.",
                            ImageUrl = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=300",
                            IsActive = true,
                            Name = "Çikolatalı Sufle",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Tatlı",
                            Description = "Espresso ile ıslatılmış savoyer bisküvileri ve mascarpone kremasıyla hazırlanan orijinal İtalyan tiramisusu.",
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=300",
                            IsActive = true,
                            Name = "Tiramisu",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Kahve",
                            Description = "Espresso ile ince dokulu kadifemsi sıcak sütün mükemmel buluşması.",
                            ImageUrl = "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?q=80&w=300",
                            IsActive = true,
                            Name = "Flat White",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Kahve",
                            Description = "Zengin espresso, çikolata sosu, sıcak süt ve krema şöleni.",
                            ImageUrl = "https://images.unsplash.com/photo-1534778101976-62847782c213?q=80&w=300",
                            IsActive = true,
                            Name = "Caffe Mocha",
                            Price = 105.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Kahve",
                            Description = "18 saat boyunca soğuk suda demlenmiş, yumuşak içimli soğuk filtre kahve.",
                            ImageUrl = "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=300",
                            IsActive = true,
                            Name = "Cold Brew",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Tatlı",
                            Description = "İçi ıslak, bol çikolatalı ve ceviz parçacıklı leziz brownie dilimi.",
                            ImageUrl = "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?q=80&w=300",
                            IsActive = true,
                            Name = "Çikolatalı Brownie",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Tatlı",
                            Description = "Ceviz, havuç ve tarçın eşliğinde ev yapımı kıvamında leziz kek dilimi.",
                            ImageUrl = "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?q=80&w=300",
                            IsActive = true,
                            Name = "Havuçlu Tarçınlı Kek",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Tatlı",
                            Description = "Karamelize elma dolgusu ve tereyağlı çıtır hamuruyla servis edilen dilim tart.",
                            ImageUrl = "https://images.unsplash.com/photo-1508737027454-e6454ef45afd?q=80&w=300",
                            IsActive = true,
                            Name = "Elmalı Tart",
                            Price = 90.00m
                        });
                });

            modelBuilder.Entity("cafe.Models.OrderItem", b =>
                {
                    b.HasOne("cafe.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cafe.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cafe.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
